name = "dash-queue-worker"
main = "src/worker.ts"
compatibility_date = "2023-10-21"

workers_dev = false

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

services = [
  { binding = "COLLECTER", service = "dash-data-collector"},
  { binding = "SAVER", service = "dash-data-saver"}
]

[[queues.consumers]]
binding = "QUEUE"
queue = "crawler-queue"
max_concurrency = 1
