name = "collect-worker"
main = "src/worker.ts"
compatibility_date = "2023-09-25"

compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

browser = { binding = "BROWSER", type = "browser" }

[[queues.consumers]]
queue = "crawler-queue"
max_batch_timeout = 30 

[[queues.producers]]
queue = "crawler-queue"
binding = "CRAWLER_QUEUE"

[triggers]
crons = [ "0 */6 * * *"  ]

