name = "dash-data-saver"
main = "src/worker.ts"
compatibility_date = "2023-10-14"

logpush = true
workers_dev = false

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "event-products"
database_id = "c19f1792-cbbb-4cf5-92f0-8a9ee0147123"
migrations_dir = "migrations"
