name = "dash-data-saver"
main = "src/worker.ts"
compatibility_date = "2023-10-14"

logpush = true
workers_dev = false

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "event-products"
database_id = "befe6c27-61d8-4d3a-a353-99f6ea9cdb9f"
migrations_dir = "migrations"
