name = "dash-data-collector"
main = "src/worker.ts"
compatibility_date = "2024-04-09"

compatibility_flags = [ "nodejs_compat" ]
logpush = true
workers_dev = false

browser = { binding = "BROWSER", type = "browser" }
