name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - '.github/**'
      - "!.github/workflows/deploy.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
        matrix:
            directory: 
                - dash-queue-worker
                - dashboard
                - data-collector
                - data-saver

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ matrix.directory }}
        