name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
        matrix:
            directory: 
                - dash-queue-worker
                - dashboard
                - data-collector
                - data-saver

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ matrix.directory }}
        