name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - name: migration
        run: |
          pnpm  wrangler d1 migrations apply event-products --local
        working-directory: ./data-saver
      - name: test
        run: |
          pnpm turbo test
